### ISSUE TITLE
怎么用啊兄弟

### ISSUE THREAD

**Issue by sci268** [c653d0/chaoxingDownloadPdf#1]
使用方法能介绍一下么

**Comment by c653d0** [comment]
有代码运行环境的话，我更新了readme，可以直接跟着教程用。没有运行环境的话，等我打包。

**Comment by c653d0** [comment]
可以看我的[另一个项目](https://github.com/c653d0/chaoxingDownloadPdf-compose)，这个里面有打包好的可执行文件。
